name: "Setup"
description: "Sets up Node and installs dependencies"

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install dependencies
      shell: bash
      run: npm i