name: "CI"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "*"

jobs:
  Tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        uses: ./.github/actions/lint

      - name: Run Tests
        uses: ./.github/actions/run-tests